question_data = [
    
    {"category":"Entertainment: Video Games",
    "type":"boolean",
    "difficulty":"easy",
    "question":"The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    
    {"category":"History",
    "type":"boolean",
    "difficulty":"medium",
    "question":"The M41 Walker Bulldog remains in service in some countries to this day.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    
    {"category":"Entertainment: Video Games",
    "type":"boolean",
    "difficulty":"hard",
    "question":"In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    
    {"category":"Geography",
    "type":"boolean",
    "difficulty":"medium",
    "question":"Antarctica is the largest desert in the world.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    
    {"category":"Entertainment: Music",
    "type":"boolean",
    "difficulty":"medium",
    "question":"&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    
    {"category":"Politics",
    "type":"boolean",
    "difficulty":"hard",
    "question":"Joko Widodo has appeared in the cover of a TIME magazine.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    
    {"category":"Celebrities",
    "type":"boolean",
    "difficulty":"easy",
    "question":"Marilyn Monroe was born on July 1, 1926.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    
    {"category":"Entertainment: Cartoon & Animations",
    "type":"boolean",
    "difficulty":"easy",
    "question":"Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    
    {"category":"Entertainment: Film",
    "type":"boolean",
    "difficulty":"medium",
    "question":"The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    
    {"category":"Entertainment: Music",
    "type":"boolean",
    "difficulty":"medium",
    "question":"Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
    "correct_answer":"True",
    "incorrect_answers":["False"]}
]